### ISSUE TITLE
四川IPTV

### ISSUE THREAD

**Issue by pxg719** [riverscn/easyiptv#3]
四川IPTV是在机顶盒上用DHCP进行鉴权认证的。目前已在Openwrt上获取了IPTV的ip地址，单线复用在电脑端和电视APP上可以正常观看直播，但还不能用原电信配的机顶盒观看直播和点播。不知道能否用你这个方法解决机顶盒观看的问题。

**Comment by pxg719** [comment]
我的邮箱：124044337@qq.com

**Comment by riverscn** [comment]
原理上应该没问题，你可以试试。

pxg719 <notifications@github.com> 于2020年4月12日周日 下午1:15写道：

**Comment by pxg719** [comment]
可否将iptvhelper.ipk及相关软件包发一份给我试试？谢谢！

**Comment by riverscn** [comment]
release 里就是啊，去下载就好了

**Comment by pxg719** [comment]
源码的压缩包文件（openwrt-iptvhelper-master.zip）？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shun Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 晚上9:46
收件人:&nbsp;"riverscn/openwrt-iptvhelper"<openwrt-iptvhelper@noreply.github.com&gt;;
抄送:&nbsp;"开天辟地"<124044337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3)





 
release 里就是啊，去下载就好了

**Comment by riverscn** [comment]
https://github.com/riverscn/openwrt-iptvhelper/releases

你是第一次用github?

**Comment by pxg719** [comment]
1.iptvhelp软件包已下载并安装到Openwrt上，按照你文档所述进行了设置，可是机顶盒还是无法接入内网观看，卡在鉴权画面。查看路由器日志有如下内容：
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: reloading
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: stopped
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: starting
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: instance starting
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox mac=xx:13:46:40:87:xx(机顶盒mac)
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox DNS redierct enabled
Wed Apr 15 22:00:10 2020 user.notice root: iptvhelper.default: topbox ipset enabled
2.上述现象不知是什么原因，请指点。
3.四川电信iTV是用光猫桥接后在机顶盒通过DHCP进行认证和鉴权的，现在通过路由器认证鉴权成功并获取了iptv服务器的ip地址，可以用播放器在电脑上或直播APP在电视上观看。
&nbsp; 谢谢!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shun Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:27
收件人:&nbsp;"riverscn/openwrt-iptvhelper"<openwrt-iptvhelper@noreply.github.com&gt;;
抄送:&nbsp;"开天辟地"<124044337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3)





 
https://github.com/riverscn/openwrt-iptvhelper/releases
 
你是第一次用github?

**Comment by riverscn** [comment]
dhcp权鉴要手动设置，你去网上找找同地区的人的设置经验

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: pxg719 <notifications@github.com>
发送时间: Wednesday, April 15, 2020 11:57:12 PM
收件人: riverscn/openwrt-iptvhelper <openwrt-iptvhelper@noreply.github.com>
抄送: Shun Li <riverscn@gmail.com>; Comment <comment@noreply.github.com>
主题: Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3)


1.iptvhelp软件包已下载并安装到Openwrt上，按照你文档所述进行了设置，可是机顶盒还是无法接入内网观看，卡在鉴权画面。查看路由器日志有如下内容：
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: reloading
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: stopped
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: starting
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: instance starting
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox mac=xx:13:46:40:87:xx(机顶盒mac)
Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox DNS redierct enabled
Wed Apr 15 22:00:10 2020 user.notice root: iptvhelper.default: topbox ipset enabled
2.上述现象不知是什么原因，请指点。
3.四川电信iTV是用光猫桥接后在机顶盒通过DHCP进行认证和鉴权的，现在通过路由器认证鉴权成功并获取了iptv服务器的ip地址，可以用播放器在电脑上或直播APP在电视上观看。
&nbsp; 谢谢!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shun Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 上午9:27
收件人:&nbsp;"riverscn/openwrt-iptvhelper"<openwrt-iptvhelper@noreply.github.com&gt;;
抄送:&nbsp;"开天辟地"<124044337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3)






https://github.com/riverscn/openwrt-iptvhelper/releases

你是第一次用github?

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

―

**Comment by pxg719** [comment]
手动设置路由器还是机顶盒？



---原始邮件---
发件人: "Shun Li"<notifications@github.com&gt;
发送时间: 2020年4月16日(周四) 上午8:33
收件人: "riverscn/openwrt-iptvhelper"<openwrt-iptvhelper@noreply.github.com&gt;;
抄送: "pxg719"<124044337@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3)




 dhcp权鉴要手动设置，你去网上找找同地区的人的设置经验 
 
 获取 Outlook for iOS<https://aka.ms/o0ukef&gt; 
 ________________________________ 
 发件人: pxg719 <notifications@github.com&gt; 
 发送时间: Wednesday, April 15, 2020 11:57:12 PM 
 收件人: riverscn/openwrt-iptvhelper <openwrt-iptvhelper@noreply.github.com&gt; 
 抄送: Shun Li <riverscn@gmail.com&gt;; Comment <comment@noreply.github.com&gt; 
 主题: Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3) 
 
 
 1.iptvhelp软件包已下载并安装到Openwrt上，按照你文档所述进行了设置，可是机顶盒还是无法接入内网观看，卡在鉴权画面。查看路由器日志有如下内容： 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: reloading 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: stopped 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper: starting 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: instance starting 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox mac=xx:13:46:40:87:xx(机顶盒mac) 
 Wed Apr 15 22:00:09 2020 user.notice root: iptvhelper.default: topbox DNS redierct enabled 
 Wed Apr 15 22:00:10 2020 user.notice root: iptvhelper.default: topbox ipset enabled 
 2.上述现象不知是什么原因，请指点。 
 3.四川电信iTV是用光猫桥接后在机顶盒通过DHCP进行认证和鉴权的，现在通过路由器认证鉴权成功并获取了iptv服务器的ip地址，可以用播放器在电脑上或直播APP在电视上观看。 
 &amp;nbsp; 谢谢! 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Shun Li"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月14日(星期二) 上午9:27 
 收件人:&amp;nbsp;"riverscn/openwrt-iptvhelper"<openwrt-iptvhelper@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"开天辟地"<124044337@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [riverscn/openwrt-iptvhelper] 四川IPTV (#3) 
 
 
 
 
 
 
 https://github.com/riverscn/openwrt-iptvhelper/releases 
 
 你是第一次用github? 
 
 ― 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 
 ―
